name: "web-application"
image: "nginx:alpine"
replicas: 2

ports:
  - host_port: 8080
    container_port: 80
    protocol: "tcp"

resources:
  cpu: "0.5"
  memory: "256m"

scale_policy:
  min_replicas: 1
  max_replicas: 5
  target_cpu: 70.0
  target_memory: 80.0
  cooldown_seconds: 60

health_check:
  command: ["curl", "-f", "http://localhost:80/health"]
  interval_seconds: 30
  timeout_seconds: 5
  retries: 3

environment:
  ENV: "production"
  LOG_LEVEL: "info"