# config.yaml
listen_address: ":8080"
data_dir: "./orchestrator-data"
cluster_name: "my-dev-cluster"

services:
  - name: "web-server"
    image: "nginx:latest"
    replicas: 2
    ports:
      - host_port: 80
        container_port: 80
        protocol: "tcp"
    environment:
      NGINX_ENV: "production"
    resources:
      cpu_millicores: 500  # 0.5 CPU core
      memory_bytes: 536870912  # 512MB
    scale_policy:
      min_replicas: 1
      max_replicas: 5
      target_cpu: 70.0
      target_memory: 80.0
      cooldown_seconds: 60
    health_check:
      type: "http"
      http_path: "/health"
      port: 80
      interval: 30
      timeout: 10
      retries: 3

  - name: "api-service"
    image: "my-app/api:1.0.0"
    replicas: 3
    ports:
      - host_port: 3000
        container_port: 3000
        protocol: "tcp"
    environment:
      DATABASE_URL: "postgres://localhost:5432/mydb"
      LOG_LEVEL: "debug"
    resources:
      cpu_millicores: 1000  # 1 CPU core
      memory_bytes: 1073741824  # 1GB
    scale_policy:
      min_replicas: 2
      max_replicas: 10
      target_cpu: 80.0
      cooldown_seconds: 120
    health_check:
      type: "command"
      command: ["curl", "-f", "http://localhost:3000/health"]
      interval: 30
      timeout: 15
      retries: 3